import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { NuqsAdapter } from 'nuqs/adapters/next'

const interFont = Inter({
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${interFont.className} antialiased`}>
      <body className="min-h-screen bg-navy-950 text-navy-50">
        <NuqsAdapter>{children}</NuqsAdapter>
      </body>
    </html>
  )
}
